### ISSUE TITLE
Add pre-commit hook

### ISSUE THREAD

**Issue by lucomsky** [pyupio/safety#336]
* safety version: any
* Python version: any
* Operating System: any

### Description

Add pre-commit hook to safety repository so one can use it directly in `pre-commit-config.yaml`
```yaml
---
repos:
  - repo: https://github.com/pyupio/safety.git
    rev: master
    hooks:
      - id: safety
        args: [check]
```
See https://github.com/rubik/xenon/blob/master/.pre-commit-hooks.yaml for example.
