### ISSUE TITLE
SQLAlchemy 1.4.xx can not be used

### ISSUE THREAD

**Issue by dmitry-engineer** [pyupio/safety#445]
* safety version:  2.3.5
* Python version: 3.9.6
* Operating System: Ubuntu 22.04

### Description

Safety tells that SQLAlchemy <2.0.0b1 has vulnerability. I don't want to migrate to SQLAlchemy 2. But I also can not use  1.4.x

**Comment by soltanoff** [comment]
```
+==============================================================================+
-> Vulnerability found in sqlalchemy version 1.4.44
   Vulnerability ID: 51668
   Affected spec: <2.0.0b1
   ADVISORY: Sqlalchemy 2.0.0b1 avoids leaking cleartext passwords to
   the open for careless uses of str(engine.URL()) in logs and...
   PVE-2022-51668
   For more information, please visit https://pyup.io/v/51668/f17
 Scan was completed. 1 vulnerability was found. 
+==============================================================================+
```
Yes, it is incorrect rule for detection. `SQLAlchemy` [2.0.*](https://docs.sqlalchemy.org/en/20/index.html) is currently in beta release.

**Comment by soltanoff** [comment]
@Jwomers, hi! 
May you help us?

**Comment by soltanoff** [comment]
@Jwomers, thank you for recommendation. 

```
security:
    ignore-cvss-severity-below: 0
    ignore-cvss-unknown-severity: False
    ignore-vulnerabilities:
        51668:
            reason: we don't use SQLAlchemy 2.0.*
            expires: '2024-10-21'
    continue-on-vulnerability-error: False
```

It works well.
